"""empty message

Revision ID: 82481ac1bea3
Revises: 
Create Date: 2017-06-01 22:36:27.439637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82481ac1bea3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=64), nullable=False),
    sa.Column('total_goal', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tax_deductable', sa.Boolean(), nullable=False),
    sa.Column('company_sponsorship', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('street_address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('amazon_link', sa.String(length=128), nullable=True),
    sa.Column('amazon_quantitiy', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=128), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_amount', sa.Integer(), nullable=False),
    sa.Column('tax_deductable', sa.Boolean(), nullable=False),
    sa.Column('max_people_allowed', sa.Integer(), nullable=False),
    sa.Column('public_can_help', sa.Boolean(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('photo_link', sa.String(length=64), nullable=False),
    sa.Column('logo_link', sa.String(length=64), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['Donation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=False),
    sa.Column('street_address', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('number_of_employees', sa.Integer(), nullable=False),
    sa.Column('logo_link', sa.String(length=64), nullable=False),
    sa.Column('social_handle', sa.String(length=64), nullable=True),
    sa.Column('number_of_donors', sa.Integer(), nullable=True),
    sa.Column('type_of_company', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['Challenge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('nonProfit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.ForeignKeyConstraint(['nonProfit_id'], ['nonProfit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challengers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['Challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], )
    )
    op.create_table('nonProfit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonProfit_name', sa.String(length=64), nullable=False),
    sa.Column('street_address', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('number_of_employees', sa.Integer(), nullable=False),
    sa.Column('logo_link', sa.String(length=64), nullable=False),
    sa.Column('social_handle', sa.String(length=64), nullable=True),
    sa.Column('number_of_donors', sa.Integer(), nullable=True),
    sa.Column('type_of_nonProfit', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('nonProfit')
    op.drop_table('companies')
    op.drop_table('challengers')
    op.drop_table('User')
    op.drop_table('Donation')
    op.drop_table('Company')
    op.drop_table('Challenge')
    op.drop_table('Campaign')
    # ### end Alembic commands ###
